redis_get: 
  handler: ./src/functions/apis/sample/redis_get/handler
  endpoint: /redis/:key
  method: get
  enabled: true
  #UNCOMMENT TO ATTACH MIDDLEWARE
  #EXAMPLE: middleware: middleware
  #middleware: <middleware_name>
