versioning_test: 
  handler: ./src/functions/apis/sample/versioning_test/handler
  endpoint: /version
  method: get
  enabled: true

  #ADD API VERSION
  #EXAMPLE OUTPUT: /login to /v1/login
  version: 1

  #ADD API PREFIX
  #EXAMPLE: api
  #EXAMPLE OUTPUT: /login to /api/login
  #WORKS WITH VERSION SAMPLE OUTPUT: /api/v1/login
  prefix: api

  #ADD MIDDLEWARE
  #EXAMPLE: middleware: authorizer
  #middleware: <middleware_name>
