client_register: 
  handler: ./src/functions/apis/client/register/handler
  endpoint: /register
  method: post
  enabled: true
  #UNCOMMENT TO ATTACH MIDDLEWARE
  #EXAMPLE: middleware: middleware
  #middleware: <middleware_name>

